// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// matern
double matern(double d, double range, double nu);
RcppExport SEXP CGEMEV_matern(SEXP dSEXP, SEXP rangeSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type range(rangeSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    __result = Rcpp::wrap(matern(d, range, nu));
    return __result;
END_RCPP
}
// preconditioning_info
List preconditioning_info(Environment obj, Function first_preconditioning, double nu, double range, double precond_bandwidth);
RcppExport SEXP CGEMEV_preconditioning_info(SEXP objSEXP, SEXP first_preconditioningSEXP, SEXP nuSEXP, SEXP rangeSEXP, SEXP precond_bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Environment >::type obj(objSEXP);
    Rcpp::traits::input_parameter< Function >::type first_preconditioning(first_preconditioningSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type range(rangeSEXP);
    Rcpp::traits::input_parameter< double >::type precond_bandwidth(precond_bandwidthSEXP);
    __result = Rcpp::wrap(preconditioning_info(obj, first_preconditioning, nu, range, precond_bandwidth));
    return __result;
END_RCPP
}
