// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// matern
double matern(double d, double range, double nu);
RcppExport SEXP CGEMEV_matern(SEXP dSEXP, SEXP rangeSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type range(rangeSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    __result = Rcpp::wrap(matern(d, range, nu));
    return __result;
END_RCPP
}
// preconditioning_info
List preconditioning_info(Environment obj, Function first_preconditioning, double nu, double range, double precond_bandwidth);
RcppExport SEXP CGEMEV_preconditioning_info(SEXP objSEXP, SEXP first_preconditioningSEXP, SEXP nuSEXP, SEXP rangeSEXP, SEXP precond_bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Environment >::type obj(objSEXP);
    Rcpp::traits::input_parameter< Function >::type first_preconditioning(first_preconditioningSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type range(rangeSEXP);
    Rcpp::traits::input_parameter< double >::type precond_bandwidth(precond_bandwidthSEXP);
    __result = Rcpp::wrap(preconditioning_info(obj, first_preconditioning, nu, range, precond_bandwidth));
    return __result;
END_RCPP
}
// belong_to_disk
bool belong_to_disk(NumericVector x, NumericVector center, double rad2);
RcppExport SEXP CGEMEV_belong_to_disk(SEXP xSEXP, SEXP centerSEXP, SEXP rad2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type center(centerSEXP);
    Rcpp::traits::input_parameter< double >::type rad2(rad2SEXP);
    __result = Rcpp::wrap(belong_to_disk(x, center, rad2));
    return __result;
END_RCPP
}
// missing_sites_grid_domain
LogicalVector missing_sites_grid_domain(Environment obj);
RcppExport SEXP CGEMEV_missing_sites_grid_domain(SEXP objSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Environment >::type obj(objSEXP);
    __result = Rcpp::wrap(missing_sites_grid_domain(obj));
    return __result;
END_RCPP
}
// distant_sites_grid_domain
LogicalVector distant_sites_grid_domain(Environment obj);
RcppExport SEXP CGEMEV_distant_sites_grid_domain(SEXP objSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Environment >::type obj(objSEXP);
    __result = Rcpp::wrap(distant_sites_grid_domain(obj));
    return __result;
END_RCPP
}
