# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matern <- function(d, range = 1, nu = .5) {
    .Call('CGEMEV_matern', PACKAGE = 'CGEMEV', d, range, nu)
}

preconditioning_info <- function(obj, first_preconditioning, nu, range, precond_bandwidth) {
    .Call('CGEMEV_preconditioning_info', PACKAGE = 'CGEMEV', obj, first_preconditioning, nu, range, precond_bandwidth)
}

belong_to_disk <- function(x, center, rad2) {
    .Call('CGEMEV_belong_to_disk', PACKAGE = 'CGEMEV', x, center, rad2)
}

missing_sites_grid_domain <- function(obj) {
    .Call('CGEMEV_missing_sites_grid_domain', PACKAGE = 'CGEMEV', obj)
}

distant_sites_grid_domain <- function(obj) {
    .Call('CGEMEV_distant_sites_grid_domain', PACKAGE = 'CGEMEV', obj)
}

