# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matern <- function(d, range = 1, nu = 0.5) {
    .Call('CGEMEV_matern', PACKAGE = 'CGEMEV', d, range, nu)
}

preconditioning_info <- function(obj, first_preconditioning, nu, range, precond_bandwidth) {
    .Call('CGEMEV_preconditioning_info', PACKAGE = 'CGEMEV', obj, first_preconditioning, nu, range, precond_bandwidth)
}

